config/routes.rb
Rails.application.routes.draw do
  root "tweets#new"
  resources :tweets
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def test
    render 'tweets/new'
  end
end

app/controllers/tweets_controller.rb
require 'client.rb'

class TweetsController < ApplicationController
  def index
    # Get the keyword from tweets#new
    @keyword = params[:query]
    t = MyTwitter.new
    @responses = t.getTenTweets(@keyword)
    @responses.each do |response|
      # Need to add de dupe here
      Tweet.create(text: response.text, username:response.user.screen_name)
    end
    @tweets = Tweet.last(10)
  end

  def new
  end


  def create
    @newTweet = params[:query]
    t2 = MyTwitter.new
    postTweet(@newTweet)

    # Re route to homepage tweets/new
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TM</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tweets/index.html.erb
<div class="container">
  <h1>Tweets</h1>
  <h2><%= @keyword%></h2>
  <% @tweets.each do |tweet| %>
    <br />
    <h3>Username: <%= tweet.username %></h3>
    <p><%= tweet.text %></p>
  <% end %>
  <br />
  <div class="linkcolor">
    <%= link_to "Select a new topic", new_tweet_path %>
  </div>
</div>

app/views/tweets/list.html.erb
<h1>Tweets</h1>
<h2><%= @keyword%></h2>
<% @tweets.each do |tweet| %>
  <br />
  <h3>Username: <%= tweet.username %></h3>
  <p><%= tweet.text %></p>
<% end %>
<br />
<%= link_to "Select a new topic", new_tweet_path %>

app/views/tweets/new.html.erb
<div class="container">
  <h2>Please select a topic</h2>
  <br />
  <%= form_tag("/tweets", :method => "get") do %>
    <%= radio_button_tag(:query, "#NASA", checked=true) %>
    <%= label_tag(:NASA, "Tweets about NASA") %>
    <%= radio_button_tag(:query, "#Healthcare") %>
    <%= label_tag(:Healthcare, "Tweets about Healthcare") %>
    <%= radio_button_tag(:query, "#Opensource") %>
    <%= label_tag(:OpenSource, "Tweets about Open Source") %>
    <% simple_format("/n") %>
    <%= submit_tag("Find Tweets") %>
  <% end %>
</div>

<%= form_tag("/tweetIt", :method => "post") do %>
  <%= label_tag(:query, "Enter a tweet:") %>
  <%= text_field_tag(:query) %>
  <% simple_format("/n") %>
  <%= submit_tag("Tweet it!") %>
<% end %>